
---
title: "P-Value"


output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
   

---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r xaringan-tile-view, echo=FALSE}
xaringanExtra::use_tile_view()
```


```{r xaringan-panelset, echo=FALSE}
xaringanExtra::use_panelset()
```

```{r, echo=FALSE}
xaringanExtra::use_webcam()
```

```{r xaringan-fit-screen, echo=FALSE}
xaringanExtra::use_fit_screen()
```

---
# Example

---
# P-Value

P-value: The probability that "the data" exists if the null hypothesis is True

---
# P-values in Research

[Link 1](https://digitalcommons.calpoly.edu/cgi/viewcontent.cgi?article=1571&context=cmsp)

[Link 2](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=8ccdce22f030c7361465cf09d0cf6e71103f0dd5)

[Link 3](https://www.sciencedirect.com/science/article/pii/S0140673605666305)

[Link 4](https://www.jstor.org/stable/pdf/146346.pdf)




---
